### ISSUE TITLE
Score Update

### ISSUE THREAD

**Issue by sysads** [VaisakhPradeep/fifa#1]
Hi, is it possible to have live scores or game results added?

**Comment by VaisakhPradeep** [comment]
Currently game results and link to highlights are added.  Will work on the live scores part.  Thanks

**Comment by sysads** [comment]
great but is the game result automatic or I have to manually edit the html file?

**Comment by VaisakhPradeep** [comment]
It's currently manual :/

**Comment by VaisakhPradeep** [comment]
Update: it's automatic now :)
